# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40d4929d75a1f550f71c916c6c31621381adb26cff4b3cec0cc7fbd9a12d3e4299fec68034ec88a511a01c3fa11a0ac6a7dd720647fa363e9c73591f7071995c

test:
  secret_key_base: a2307ef38ec9fe9bc569f74a8a18d1e14370354a2e4d5e61e1d693fa40b4dec6bb2aef39201e9cfc43ca1f2a45074a7645fc3c09b857910ca405a89f92004955

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
