# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1d2864e878b4f9dbcb9c0a58d90330a0941680a2080f9d3520bffc0c314c29f0015e8f42a13cd6da0a8fa77c37b0aa2959e91c3e115d71ae4aeb1ef365206a1

test:
  secret_key_base: fea9d7dc5346c8692d35df65bd6d575f025ecffb0329ed1d9b4312f04f4a6d126576ee0107e248c19675eeb6146ac40835474519447c7df841c1077727419133

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
